# AutoSpanishBlog - Base Configuration

environment: base

# Sources for topic discovery
sources:
  max_headlines_per_source: 20
  fetch_timeout: 10

# Article generation settings
generation:
  articles_per_run: 4
  levels:
    - A2
    - B1
  target_word_count:
    A2: 200
    B1: 300

# Quality gate settings
quality_gate:
  min_score: 7.5
  max_attempts: 3

# LLM configuration
llm:
  provider: anthropic  # or 'openai'
  models:
    generation: claude-sonnet-4-20250514
    quality_check: claude-haiku-4-20250323
  temperature: 0.3
  max_tokens: 4096

# Output settings
output:
  format: jekyll
  path: ./output/_posts

# Logging (overridden per environment)
logging:
  level: INFO
  format: json
  file: output/logs/app.log

# Metrics
metrics:
  enabled: true
  output: output/metrics/

# Alerts
alerts:
  enabled: false
  email: your@email.com
