# Local Development Configuration

environment: local

# Faster testing with fewer articles
generation:
  articles_per_run: 2

# Console logging for development
logging:
  level: DEBUG
  format: console  # Colored, human-readable
  file: logs/local.log

# Disable metrics in local dev
metrics:
  enabled: false

# Disable alerts in local dev
alerts:
  enabled: false
