# Production Configuration

environment: production

# Full article generation
generation:
  articles_per_run: 4

# Structured JSON logging for parsing
logging:
  level: INFO
  format: json
  file: output/logs/production.log

# Enable metrics in production
metrics:
  enabled: true
  output: output/metrics/

# Enable alerts in production
alerts:
  enabled: true
  email: ${ALERT_EMAIL}  # Override with env var
  
  # Email configuration (for SendGrid or SMTP)
  email_config:
    from: bot@autospanish.com
    smtp:
      host: smtp.sendgrid.net
      port: 587
      username: apikey
      password: ${SENDGRID_API_KEY}
  
  # Optional Telegram alerts
  telegram:
    enabled: false
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}
